from turtle import Turtle

FONT = ("Fixedsys Regular", 30, "normal")

class OpenMessage(Turtle):
    def __init__(self):
        super().__init__()
        self.hideturtle()
        self.color("red")
        self.pu()
        self.goto(-90, 0)
        self.write("B", font=FONT)
        self.color("blue")
        self.goto(-65, 0)
        self.write("r", font=FONT)
        self.color("yellow")
        self.goto(-50, 0)
        self.write("e", font=FONT)
        self.color("purple")
        self.goto(-30, 0)
        self.write("a", font=FONT)
        self.color("blue")
        self.goto(-10, 0)
        self.write("k", font=FONT)
        self.color("blue")
        self.goto(20, 0)
        self.write("O", font=FONT)
        self.color("purple")
        self.goto(50, 0)
        self.write("u", font=FONT)
        self.color("red")
        self.goto(70, 0)
        self.write("t", font=FONT)
        self.color("purple")
        self.goto(-70, -50)
        self.write("(", font=FONT)
        self.color("blue")
        self.goto(-60, -50)
        self.write("C", font=FONT)
        self.color("yellow")
        self.goto(-30, -50)
        self.write("l", font=FONT)
        self.color("red")
        self.goto(-20, -50)
        self.write("o", font=FONT)
        self.color("purple")
        self.goto(0, -50)
        self.write("n", font=FONT)
        self.color("blue")
        self.goto(20, -50)
        self.write("e", font=FONT)
        self.color("red")
        self.goto(40, -50)
        self.write(")", font=FONT)
        self.goto(-55, -80)
        self.color("white")
        self.write("Click below to start!")

class GameOverMessage(Turtle):
        def __init__(self):
            super().__init__()
            self.hideturtle()
            self.color("red")
            self.pu()
            self.goto(-90, 0)
            self.write("G", font=FONT)
            self.color("blue")
            self.goto(-60, 0)
            self.write("a", font=FONT)
            self.color("yellow")
            self.goto(-40, 0)
            self.write("m", font=FONT)
            self.color("purple")
            self.goto(-5, 0)
            self.write("e", font=FONT)
            self.color("blue")
            self.goto(20, 0)
            self.write("O", font=FONT)
            self.color("purple")
            self.goto(50, 0)
            self.write("v", font=FONT)
            self.color("red")
            self.goto(70, 0)
            self.write("e", font=FONT)
            self.color("purple")
            self.goto(90, 0)
            self.write("r", font=FONT)
            self.color("purple")
            self.goto(100, 0)
            self.write("!", font=FONT)
            self.color("white")
            self.goto(-45, -30)
            self.write("click to exit!", font=("arial", 16, "bold"))
